apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jhnlt1tf4-go
  janus-idp.io/tekton: jhnlt1tf4-go
  backstage.io/kubernetes-id: jhnlt1tf4-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jhnlt1tf4-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
