apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jhnlt1tf4-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jhnlt1tf4-go 
  name: jhnlt1tf4-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jhnlt1tf4-go 
